### PR TITLE
Merge latest mozilla master to fork + fix conflicts

### PR DESCRIPTION
**Pull request by abhijitvalluri**
Pull in latest mozilla master + fix conflicts

### CODE REVIEW

**Comment by abhijitvalluri** [comment]
@reyis4402 if you can build the code and install it on your device, then please try the code from this PR and verify that warp is enabled.

**Comment by interfect** [comment]
Looks like Mozilla's taking [a longer list of add-ons](https://addons.mozilla.org/en-US/firefox/collections/4757633/7dfae8669acc4312a65e8ba5553036/) (in Nightly) in this changeset. I've made sure everything on their list is on ours.

**Comment by interfect** [comment]
I pulled this in to my working copy and did a build, and unfortunately I can't find a `javascript.options.warp` setting in `about:config`.

**Comment by Namit-Nayan** [comment]
> Looks like Mozilla's taking [a longer list of add-ons](https://addons.mozilla.org/en-US/firefox/collections/4757633/7dfae8669acc4312a65e8ba5553036/) (in Nightly) in this changeset. I've made sure everything on their list is on ours.

@interfect did you remove(or didn't add by mistake) [ClearURLs addon](https://addons.mozilla.org/en-US/firefox/addon/clearurls/) from the list? It was there before.
I downloaded the apk uploaded by GitHub actions CI as suggested [here](https://github.com/fork-maintainers/iceraven-browser/pull/165#issuecomment-699582438) 
This version has #157  feature.(that's why I downloaded it 😀) 
And it's still on GV 80 that's why no Warp in about config.

**Pull request merged**
