### PR TITLE
Update wordmark banner for Iceraven branding

### PR DESCRIPTION
**Pull request by bbigam**
When we're ready to launch our new Iceraven branding, this PR will update the banner wordmark on the home screen and about page. Also upload the XCFs to fork-asset-sources for easy editing in the future.
Does not include a logo. We could easily add this later if we want to.
These files are properly scaled according to the instructions in fork-asset-sources/wordmark_dpi; the information in that file came from the upstream versions of these workmark banners.

### CODE REVIEW

**Comment by bbigam** [comment]
Why does Travis keeping failing on minor asset changes? Anyone know what's going on?

**Comment by abhijitvalluri** [comment]
The failure is due to a flaky test and some other tests that fail due to changes we made. I fixed all these test failures in my PR #109. The failures are not due to your asset changes. There is a flaky test that fails randomly.

**Comment by bbigam** [comment]
Thank you for explaining, and for fixing the tests!

**Comment by abhijitvalluri** [comment]
I re-ran the CI check and it passed!

**Review by interfect — APPROVED** [review]
Thanks for making these!

**Pull request merged**
