### PR TITLE
Die For Your RAM

### LINKED ISSUE #115: It is not possible to stop tabs from being unloaded in the background, even when setting relevant about:config settings, and we need a control to turn it off
## Steps to reproduce
Page reload in the background even after adding this to the config
accessibility.blockautorefresh=true
browser.tabs.disableBackgroundZombification=true
browser.tabs.unloadOnLowMemory=false
browser.meta_refresh_when_inactive.disabled=true

Page is still reloading in the background. On old version of ff version 68, i do this step and it does not reload my pages. Does about:config working properly?

### Expected behavior
Open about 20 to 30 tabs.
Page reloading if you started to browse to all of your tabs.

### Device information
Xiaomi Redmi Note 8 128GB 4GB ram
* Android device: 9.0 Pie
* Fenix version: fork 10 latest

### PR DESCRIPTION
**Pull request by interfect**
### Pull Request checklist

- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- This has been tested manually
- [X] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

Screenshot_20200925-212518_Iceraven_Preview

This adds a setting to fix #115 by letting you hide all memory pressure messages from the part of the app that remembers tab page states. If you turn it off, the app will let itself be completely killed by Android before deleting any page states.

@izarsha @Namit-Nayan do either of you want to test one of these debug APKs and see if you can make it drop tabs? 
[arm64](https://files.novak.network/f/4e822f759de34744b847/?dl=1)
[arm](https://files.novak.network/f/e1328f4cb77f4f879811/?dl=1)

### CODE REVIEW

**Comment by interfect** [comment]
The setting is on by default, to preserve the normal behavior. I turned it off for the screenshot.

**Comment by Namit-Nayan** [comment]
@interfect app was able to keep 7-8 tabs fine on my 3 gb ram device, Though I had to disable swipe to switch tabs for it(got idea from leak canary trace). Else it was only keeping around 3-4.

Also there is some other memory leak when having both private and normal tabs open.
Attaching leak trace. (1st one is swipe gesture related, second is another one)
[leaks.txt](https://github.com/fork-maintainers/iceraven-browser/files/5286867/leaks.txt)

Edit: Second leak seems to happen in another situations too.
Also after disabling swipe to hide toolbar , I don't face  #150 .

**Comment by interfect** [comment]
I don't think this PR is really able to be the source of new memory leaks (which I guess are references to things wandering into places they never get dropped). All the Kotlin code is just using locals. Though it sounds like we might have a leak problem with some of the gesture implementations?

If the tab states are already growing in memory over time, turning off dropping their data will let them do that until they get the app killed, but I think that's kind of the point of having a setting to not drop the tabs.

So it sounds like this is working, I think?

**Comment by abhijitvalluri** [comment]
> @interfect app was able to keep 7-8 tabs fine on my 3 gb ram device, Though I had to disable swipe to switch tabs for it(got idea from leak canary trace). Else it was only keeping around 3-4.
> 
> Also there is some other memory leak when having both private and normal tabs open.
> Attaching leak trace. (1st one is swipe gesture related, second is another one)
> [leaks.txt](https://github.com/fork-maintainers/iceraven-browser/files/5286867/leaks.txt)
> 
> Edit: Second leak seems to happen in another situations too.

Regarding the memory leaks, I think they are pre-existing: https://github.com/mozilla-mobile/fenix/issues/13785
https://github.com/mozilla-mobile/fenix/issues/12302 has lot of references of memory leaks.

**Comment by Namit-Nayan** [comment]
> I don't think this PR is really able to be the source of new memory leaks (which I guess are references to things wandering into places they never get dropped). 

Yes. I just wrote what I observed. Thanks though, at least now I know sacrificing some gestures helps with keeping tabs.

> So it sounds like this is working, I think?

Yes.

**Comment by phanirithvij** [comment]
This should be disabled by default.


I lost a 20mins worth of a github comment I typed on my mobile. When I just opened a new tab to grab the link to reference it in the comment and came back it's all gone. Github even forgot about the comment text. 


Edit: 3 months later, this isn't even working anymore, when I go to a different app and come back even in less than 5 seconds, the open tab turns black and takes 10 seconds to start reloading.

**Pull request merged**
