### PR TITLE
SPAM

### PR DESCRIPTION
**Pull request by Utkarshdubey44**
Closed due to spam.

### CODE REVIEW

**Comment by hbarsaiyan** [comment]
you are posting to the wrong repo

**Comment by Vikaskhurja** [comment]
Where should I post this

**Comment by hbarsaiyan** [comment]
Do you even read

**Comment by Vikaskhurja** [comment]
Contact me at - utkarshdubey44@gmail.com

**Comment by hbarsaiyan** [comment]
WTF just stop spamming already!

**Comment by Utkarshdubey44** [comment]
> > Where should I post this
> 
> Keep it to yourself and close the pr

Mind your own Business Sir

**Comment by Vikaskhurja** [comment]
Lund le le mera madhrchod @hbarsaiyan

**Comment by hbarsaiyan** [comment]
@abhijitvalluri @interfect ban these clowns from repo please

**Comment by Namit-Nayan** [comment]
@abhijitvalluri it seems like the Hacktoberfest spam and no idea why they are doing here, probably confused. And definitely lacking respect for others.
Will the GitHub actions build apk everytime ? because it will be waste of resources.

**Comment by abhijitvalluri** [comment]
Only collaborators can access this repo for the next day. Closing due to spam and also foul language used by Vikaskhurja.

**Pull request closed without merging**
