### PR TITLE
Modify tabs tray layout to have new tab button at the bottom when toolbar (i.e. URL bar) is at the bottom + display favicon in tabs tray

### PR DESCRIPTION
**Pull request by abhijitvalluri**
Enabled a different layout for the tabs tray when the toolbar is at the bottom. This new layout has the new tab button (+) at the bottom of the tray, along with the top bar, that has the tabs for "Default tabs" and "Private tabs". The advantage of this change is that the button to add a new tab/private tab is always near the place the toolbar is. So, if the toolbar is at the top, the button is at the top, and if the toolbar is at the bottom the button is also at the bottom. This helps users avoid moving around the screen to reach the buttons!

This new layout uses a custom `TopSheetBehavior` implementation that reverses the standard `BottomSheetBehavior` so it closes when it slides up. The layout of the tabs, save to collection button and synced tabs (if enabled to show in tabs tray) is also reversed. 

Also, tweaked the layout for the tab items, so that the margins are a bit narrower and the item is more compact.

### CODE REVIEW

**Comment by abhijitvalluri** [comment]
Implemented a new feature to make the tabs tray look even more like the old (Fennec) version. Display tab's favicon in the UI! So, each site now has its favicon visible as well.

### Screenshots

**Comment by interfect** [comment]
This looks good!

One comment is that I think the reason that the tab tray only covers part of the screen is so that none of the tabs get too far from the bottom, right? I'm not really sure how it would work exactly, but I feel like the tabs themselves might want to come down more in the descending-from-the top version, somehow.

I'll try using it for a while and see if I or anyone else can articulate any real proposed change.

**Comment by interfect** [comment]
It looks like the little tab thumbnails are saved across app restarts, but the favicons aren't.

**Comment by interfect** [comment]
OK, it seems to be pretty easy to reach from the bottom so far. If you have enough tabs the tray opens full screen anyway, and when it's partway open the buttons are actually closer to where my thumb sits than if they were at the bottom.

**Comment by interfect** [comment]
The only thing I might change would be tab ordering. New tabs show up at the top of the list, and not the bottom, when the list comes down from the top. I would want them at the bottom.

**Comment by abhijitvalluri** [comment]
Yeah, I noticed that the favicons are not saved across app restarts, which is a shame. They get reloaded when you reload the tabs. Also, it seems, at least for me, that if there are 4 or more tabs open the tab tray opens fully by default. 

I will look into the tab ordering. The current tab ordering is the standard tab ordering in the old Fennec version where the newest tabs get appended to the end. So, when the toolbar is at the top and tab tray comes from the bottom, the new tab is appended at the bottom. When the toolbar is at the bottom and tab tray comes from the top, the new tab is appended at the top. I can look into changing this to make the newest tab the start of the list.

Also, I will have to do more tweaking to allow users to configure the layout of the tab tray. A new issue (#56) is already raised asking me to make this configurable! So, at least some people liked the new Fenix layout.

**Pull request merged**
